### ISSUE TITLE
play slowly

### ISSUE THREAD

**Issue by FreshLuoBoGan** [MonaSolutions/librtmfp#12]
librtmp TestClient  +  Monaserver  + http://raspi.monaserver.ovh/MonaClients/VideoPlayer/   
 ./TestClient --p2pWrite --url=rtmfp://ip:1975/live/12 --netgroup=G:027f0201010103010c050e74657374011b00 --logFile=testPubli.log --mediaFile=out1.flv
play slowly

**Comment by thomasjammet** [comment]
Hi,

Please don't spam the issues and write a complete description. 
I have answered you in the issue #13.
