### ISSUE TITLE
why TestClient NO TIME CONTROL; Please tell me how to deal it.

### ISSUE THREAD

**Issue by FreshLuoBoGan** [MonaSolutions/librtmfp#13]

**Comment by thomasjammet** [comment]
Hi,

TestClient is here only for testing, you should use ffmpeg to have a complete working solution which allows to play and publish a stream smoothly. Also are you trying to play or publish with Testclient? Give us more details if you want us to help you.

**Comment by FreshLuoBoGan** [comment]
ok,  Have ffmpeg Integrate the rtmfp?  I want send raw h264 by rtmfp, so I want to use librtmfp to send.  librtmp include TestClient,  can  the librtmp control TIME?

**Comment by thomasjammet** [comment]
Here are the instructions to compile ffmpeg with librtmfp : 
https://github.com/MonaSolutions/librtmfp/blob/master/INSTALL.md

No TestClient is not good if you want to deal with time, it reads the input file with a fixed rate of 81Kb/50ms so it results in an unexpected behavior on player side.
We could write a better publish feature in TestClient but it's waste of time as ffmpeg does it better.

**Comment by FreshLuoBoGan** [comment]
OK, thank you. If i have free time ,I would like to make TestClient better.

**Comment by FreshLuoBoGan** [comment]
I will try ffmpeg to get rtmfp

**Comment by FreshLuoBoGan** [comment]
What is "P2P direct communication only "? Is  it  NO video or audio? and how to get peerId?

**Comment by ROBERT-MCDOWELL** [comment]
p2p is like webrtc in javascript, 2 computers get an peerID at a rendez-vous point like monaserver and connect then directly to each others.

**Comment by ROBERT-MCDOWELL** [comment]
@thomasjammet
It would maybe worth to remove the testClient and replace it with an ffmpeg example? contributions open!!
