### ISSUE TITLE
Failed to publish big i-frames

### ISSUE THREAD

**Issue by laobubu** [MonaSolutions/librtmfp#2]
I'm trying to publish big_buck_bunny, to a RTMFP NetGroup, with FFmpeg+librtfmp. When FFmpeg encounters big i-frames, it fails to publish, resulting bad images in Flash players.

## FFmpeg publish

```sh
./ffmpeg -re -i big_buck_bunny_720p_h264.mov -c:v libx264 -c:a aac -b:v 1000k --netgroup G:027f0201010103010c020e61011b00 -f flv rtmfp://<IPv6Address>:1935/live/test
```

Everything works well until a big i-frame occurs. Seems that librtmfp cannot transmit big user data chunk correctly, and fail to send big i-frames.

![z.gif](https://i.loli.net/2017/11/16/5a0d48000fc27.gif)

## TestClient

```sh
ffmpeg -i big_buck_bunny_720p_h264.mov -c:v libx264 -c:a aac -b:v 1000k -f flv test.flv
./TestClient --p2pWrite --url=rtmfp://<IPv6Address>/live/test --netgroup=G:027f0201010103010c020e61011b00 --logFile=testPubli.log --mediaFile=test.flv
```

Using your Flash VideoPlayer: <http://raspi.monaserver.ovh/MonaClients/VideoPlayer/>

TestClient repeatedly outputs `DEBUG Main.c[176] Buffer too short, increasing...`
And finally, when it encounters the first big i-frame, TestClient exits, with following log.
Players can not even see the river's flow.

```
11/16 15:37:01.3        DEBUG Main.c[176] Buffer too short, increasing...
11/16 15:37:01.4        DEBUG Main.c[176] Buffer too short, increasing...
11/16 15:37:01.4        ERROR Main.c[181] The current stream size is too long, exiting...
11/16 15:37:01.4        INFO Main.c[444] Closing connection...
11/16 15:37:01.4        INFO Invoker.cpp[404] Deleting connection 1...
11/16 15:37:01.4        INFO RTMFPSession.cpp[520] Deletion of the listener to G:027f0201010103010c020e61011b
11/16 15:37:01.4        INFO Publisher.cpp[99] Publication test stopped
11/16 15:37:01.4        INFO Invoker.cpp[353] Invoker memory release
11/16 15:37:01.4        NOTE Invoker.cpp[356] Invoker stopped
```

Video File: <http://mirror.bigbuckbunny.de/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov>
OS: Ubuntu 16.04 x64
Versions:
 - librtmfp [f4e6fe573f](https://github.com/MonaSolutions/librtmfp/tree/f4e6fe573f0aefd070802238aab41e21471e3399)
 - ffmpeg [17831167fc](https://github.com/thomasjammet/FFmpeg/tree/17831167fca58a2034f222e5a3e83ed8f6ce8e2e)
 - MonaServer [f11de24468](https://github.com/MonaSolutions/MonaServer/tree/f11de244683e931490805d05a2dbe938f99db30a)

**Comment by thomasjammet** [comment]
Hi, 

There was a misunderstanding of ffmpeg behavior with publishing, it could miss big packets, I have just made a correction. 
Can you try again?

Also please consider that NetGroup is not well suited for high quality video, unless you are sure that all your users have an excellent bandwidth.

Thank you for your report.

Regards

**Comment by laobubu** [comment]
Hello.

Thank you. Just tested with 420555abfceb12dfc0c4858473f31a95aa30b0a7 and it works like a charm now!

This high bitrate video is only used to reproduce the issue. I will use a proper bitrate while streaming. Thank you again for your great job!

**Comment by thomasjammet** [comment]
You're welcome!
