### ISSUE TITLE
Do you hava sample for play rtmfp stream

### ISSUE THREAD

**Issue by jobsguo** [MonaSolutions/librtmfp#3]
Do you have a sample for play rtmfp stream?
when I  exceute such script below:
TestClient --p2pWrite --url=rtmfp://127.0.0.1:1985/live/G001 --netgroup=G:027f0201010103010c050e47313030011b00 --logFile=testPublihFlvGroup.log --mediaFile=1.flv

then I  input params in http://raspi.monaserver.ovh/MonaClients/VideoPlayer/
url = rtmfp://127.0.0.1:1985/test123
groupName=G001
netgroupid=G:027f0201010103010c050e47313030011b00
then start connect

the log show below, it seems work ok,but I can not display video.

Initialization of the video player
Connection to 'rtmfp://127.0.0.1:1985' (stream name : test123)
NetConnection event : NetConnection.Connect.Success
Start playing stream test123
NetStream event : NetStream.Play.Reset
NetStream event : NetStream.Play.Start
Connection to 'rtmfp://127.0.0.1:1985' (stream name : test123)
NetConnection event : NetConnection.Connect.Closed
NetConnection event : NetConnection.Connect.Success
GroupSpec created : G:027f0201010103010c050e47313030011b00
NetConnection event : NetStream.Connect.Success
NetStream event : NetStream.Play.Reset
NetStream event : NetStream.Play.Start
NetConnection event : NetGroup.Connect.Success
NetGroup event : NetGroup.Neighbor.Connect
NetGroup event : NetGroup.MulticastStream.PublishNotify
![rtmfp-1](https://user-images.githubusercontent.com/1125139/33527203-6e925768-d887-11e7-8869-296ad57bbb51.png)

**Comment by jobsguo** [comment]
sorry ,I wrong, the url is error,
I should type:rtmfp://127.0.0.1:1985/live/G001  
it is ok!
![Uploading rtmfp-3.png…]()

**Comment by thomasjammet** [comment]
Fine! Please use ffmpeg for production use, TestClient is just for testing, there is no time control like the ffmpeg ["-re" option](https://ffmpeg.org/ffmpeg.html#toc-Advanced-options).

**Comment by FreshLuoBoGan** [comment]
how tio control time? I want to use librtmfp

**Comment by FreshLuoBoGan** [comment]
why TestClient NO TIME CONTROL; Please tell me how to deal it.
