### ISSUE TITLE
Cannot compile with libx264

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [MonaSolutions/librtmfp#5]
I get
libavcodec/libavcodec.so: undefined reference to `x264_bit_depth'
libavcodec/libavcodec.so: undefined reference to `x264_encoder_open_152'
 when --enable-libx264
any idea?
thanks

**Comment by thomasjammet** [comment]
Did you install libx264 developer version? (x264-devel or x264-dev)

**Comment by ROBERT-MCDOWELL** [comment]
I installed last x264 git and compiled myself

**Comment by ROBERT-MCDOWELL** [comment]
issue fixed it can be cloase thanks

**Comment by ROBERT-MCDOWELL** [comment]
issue fixed, can be closed thanks
