### ISSUE TITLE
linux pre req

### ISSUE THREAD

**Issue by rdp** [MonaSolutions/librtmfp#7]
Seems it needs openssl as a dependency, might be nice to call that out in the INSTALL.md if it's the case...

**Comment by ROBERT-MCDOWELL** [comment]
agree

**Comment by thomasjammet** [comment]
Sorry this is very late but I have just [updated INSTALL.md](https://github.com/MonaSolutions/librtmfp/commit/59dab341ba78020a451fe94f9a3cb2e9b8a3a87f#diff-7d442b7eb49f5fc377f51e74b291cfc1)
