### ISSUE TITLE
Compile librtmfp as static on Linux

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [MonaSolutions/librtmfp#9]
Hi there, is it possible to compile librtmfp.a? I tried to compile ffmpeg as static
but obviously it needs librtmfp compiled as static too.
Thanks!

**Comment by thomasjammet** [comment]
Hi Robert,

Yes, I have just updated the makefile so it now creates the .ar too.

You're welcome !

**Comment by ROBERT-MCDOWELL** [comment]
Excellent Thomas, thanks you very much

**Comment by ROBERT-MCDOWELL** [comment]
I forgot to ask of how to compile ffmpeg with librtmfp as static?

**Comment by ROBERT-MCDOWELL** [comment]
I just noticed also that after make install librtmfp.ar is not present in /usr/lib64 nor /usr/lib.
is it the normal behavior?

**Comment by ROBERT-MCDOWELL** [comment]
Excellent Thomas, thank you very much! :)
How to compile your ffmpeg fork with librtmfp as static?
I just noticed also that after make install librtmfp.ar is not present in /usr/lib64 nor /usr/lib.
is it the normal behavior?

**Comment by thomasjammet** [comment]
Hi,

This should be something like this : http://www.alamtechstuffs.com/ffmpegcompile_with_x264/
I will try later to do the same with librtmfp.
I thinks it's normal to not have the static library in /usr/lib as it is used for shared libraries.

**Comment by thomasjammet** [comment]
I have tried a right command is :

`./configure --disable-x86asm --enable-librtmfp --enable-libspeex --enable-libx264 --enable-libx265 --enable-gpl --extra-ldflags='-L/home/tj/dev/librtmfp/lib' --extra-cflags='-I/home/tj/dev/librtmfp/include' --extra-libs='-l:librtmfp.a -lstdc++ -lm -lssl -lcrypto'`

Note that without modifying the ffmpeg configure file you'll have to do "make install" into librtmfp's directory before the command below (pkgconfig is searching for the librtmfp dynamic library).
Also you can remove the -fPIC and -share flags from the librtmfp gcc commands, this is not optimized for static libraries.

I am curious, for which reason you need to compile ffmpeg statically?

**Comment by thomasjammet** [comment]
(I have just commited a correction of librtmfp Makefile to change from .ar to .a)

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks for the info, I'm trying to create an installer which includes a portable ffmpeg for 32 and 64 bit to avoid any complex differences between linux distributions. As I'm not a cross compile expert it's very possible I'm using the wrong way

**Comment by ROBERT-MCDOWELL** [comment]
your configure options works perfectly on my side

**Comment by ROBERT-MCDOWELL** [comment]
btw, why not to send a PR to official ffmpeg git to add librtmfp option?

**Comment by thomasjammet** [comment]
> 
> 
> btw, why not to send a PR to official ffmpeg git to add librtmfp option?

It's in progress, I will tell you when the PR is accepted ;-)
